### ISSUE TITLE
NullPointerException after Restart and Reload app:

### ISSUE THREAD

**Issue by tscheims1** [shylux/ch.bfh.bti7081.s2015.rot#26]
used by: 
java.lang.NullPointerException
    at ch.bfh.bti7081.s2015.red.PatientApp.Model.Activity.getStateName(Activity.java:35)
    at ch.bfh.bti7081.s2015.red.PatientApp.Presenter.LifeUpDetailPreseter.<init>(LifeUpDetailPreseter.java:39)
    at ch.bfh.bti7081.s2015.red.PatientApp.View.NavigatorUI.init(NavigatorUI.java:138)
    at com.vaadin.ui.UI.doInit(UI.java:646)
    at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:214)
    at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74)
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1408)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:350)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
    at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:172)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
    at java.lang.Thread.run(Thread.java:745)
[ch.bfh.bti7081.s2015.red.PatientApp.Model.GpsActivity@944f48f] Status Nr. (0):InProgress
[ch.bfh.bti7081.s2015.red.PatientApp.Model.GpsActivity@7831bd7] Status Nr. (1):InProgress
[ch.bfh.bti7081.s2015.red.PatientApp.Model.GpsActivity@3bc9fff] Status Nr. (2):InProgress
## [ch.bfh.bti7081.s2015.red.PatientApp.Model.GpsActivity@46be11ec] Status Nr. (3):InProgress

activity GetStateName

bitte fixe

**Comment by tanns2** [comment]
Isch gfixet i mim Branch: LifeUpProgress
